export const LAY_DANH_SACH_HE_THONG_RAP = "LAY_DANH_SACH_HE_THONG_RAP";
export const LAY_THONG_TIN_CUM_RAP = "LAY_THONG_TIN_CUM_RAP";
export const LAY_THONG_TIN_LICH_CHIEU = "LAY_THONG_TIN_CUM_RAP";

