export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';
export const XOA_NGUOI_DUNG = 'XOA_NGUOI_DUNG';
export const CAP_NHAT_THONG_TIN_NGUOI_DUNG = 'CAP_NHAT_THONG_TIN_NGUOI_DUNG';
export const DANG_NHAP = 'DANG_NHAP';
export const DANG_KY = 'DANG_KY';
export const LAY_THONG_TIN_NGUOI_DUNG = 'LAY_THONG_TIN_NGUOI_DUNG';